---
all:
  children:
    wbxes:
      hosts:
        leaf04:
          ansible_host: 100.109.1.19
        leaf03:
          ansible_host: 100.109.1.18
      vars:
        ansible_user: admin # To be updated
        ansible_connection: local
        ansible_network_os: sros
        sros_user: anton
        sros_password: anton123
        sros_new_user: backup
        sros_new_password: backup123bullshit 
        target_version: 394
        sros_image_size: 62679744
        sros_src_image_name: both.tim
        sros_dst_image_name: both541U91.tim
...

