---
all:
  children:
    wbxes:
      hosts:
        leaf04:
          ansible_host: 100.109.1.19
        leaf03:
          ansible_host: 100.109.1.18
          # Here you can override vars below
      vars:
        ansible_connection: local
        ansible_network_os: sros
        # Your login
        sros_user: anton
        # Your current password
        sros_password: anton123
        # User whose password needs to be updated
        sros_updated_user: backup
        # Desired password length
        sros_updated_pw_length: 12
        target_version: 394
        sros_image_size: 62679744
        sros_src_image_name: both.tim
        sros_dst_image_name: both541U91.tim
...

